- .github/workflows/backend-ci.yml
- .github/workflows/backend-release.yml
- backend/src/test/kotlin/me/elgregos/escapecamp/EscapeCampApplicationTests.kt
> 👷 Configure Github actions correctly for backend

- backend/build.gradle.kts
- backend/src/main/kotlin/me/elgregos/escapecamp/game/api/GameController.kt
> ✨ Create a default endpoint to test deployment

- .github/workflows/backend-release.yml
- backend/build.gradle.kts
> 🔖 Review backend release actions

- .github/workflows/backend-release.yml
- backend/build.gradle.kts
> 🔖 Set git repository path for release plugin

- .github/workflows/backend-release.yml
- clevercloud/gradle.json
> 🚀 Add Clever Cloud config

- backend/build.gradle.kts
- backend/docker-compose.yml
- backend/src/integrationTest/kotlin/me/elgregos/escapecamp/EscapeCampApplicationTests.kt
- backend/src/integrationTest/kotlin/me/elgregos/escapecamp/utils/BaseIntegrationTest.kt
- backend/src/integrationTest/kotlin/me/elgregos/escapecamp/utils/extensions/postgres/PostgreSQLContainerHandler.kt
- backend/src/integrationTest/kotlin/me/elgregos/escapecamp/utils/extensions/postgres/PostgreSQLExtension.kt
- backend/src/integrationTest/kotlin/me/elgregos/escapecamp/utils/test/BaseIntegrationTest.kt
- backend/src/test/kotlin/me/elgregos/escapecamp/EscapeCampApplicationTests.kt
> ✅ Configure integration tests

- backend/build.gradle.kts
- backend/src/main/kotlin/me/elgregos/escapecamp/EscapeCampApplication.kt
> 🔧 Review SpringBoot main class config

- backend/build.gradle.kts
> ➕ Add events-k dependency

- .run/EscapeCampApplicationKt.run.xml
- backend/src/integrationTest/kotlin/me/elgregos/escapecamp/game/api/AddTeamApiStepDefinition.kt
- backend/src/integrationTest/kotlin/me/elgregos/escapecamp/game/api/CreateGameApiStepDefinition.kt
- backend/src/integrationTest/kotlin/me/elgregos/escapecamp/game/api/GameClient.kt
- backend/src/integrationTest/resources/features.game.api/02-add-team-api.feature
- backend/src/main/kotlin/me/elgregos/escapecamp/config/security/jwt/TokenProvider.kt
- backend/src/main/kotlin/me/elgregos/escapecamp/config/sse/ServerSentEventConfig.kt
- backend/src/main/kotlin/me/elgregos/escapecamp/config/sse/ServerSentEventService.kt
- backend/src/main/kotlin/me/elgregos/escapecamp/game/api/GameController.kt
- backend/src/main/kotlin/me/elgregos/escapecamp/game/api/dto/GameStreamEvent.kt
- backend/src/main/kotlin/me/elgregos/escapecamp/game/domain/entity/Game.kt
- backend/src/main/kotlin/me/elgregos/escapecamp/game/domain/event/GameAggregate.kt
- backend/src/main/kotlin/me/elgregos/escapecamp/game/domain/event/GameEvent.kt
- backend/src/main/kotlin/me/elgregos/escapecamp/game/infrastructure/event/GameServerSentEventSubscriber.kt
- backend/src/test/kotlin/me/elgregos/escapecamp/game/domain/event/GameAggregateTest.kt
- backend/src/test/kotlin/me/elgregos/escapecamp/game/domain/event/GameEvents.kt
> ✨ Start the game when 4 teams are added

- backend/src/main/kotlin/me/elgregos/escapecamp/game/domain/entity/Game.kt
- backend/src/test/kotlin/me/elgregos/escapecamp/game/domain/entity/GameTest.kt
- backend/src/test/kotlin/me/elgregos/escapecamp/game/domain/entity/Games.kt
- backend/src/test/kotlin/me/elgregos/escapecamp/game/domain/entity/Riddles.kt
- backend/src/test/kotlin/me/elgregos/escapecamp/game/domain/entity/Teams.kt
> 🐛 Avoid index out of bound on riddle assignment

- backend/build.gradle.kts
- backend/src/integrationTest/kotlin/me/elgregos/escapecamp/game/api/GameClient.kt
- backend/src/integrationTest/kotlin/me/elgregos/escapecamp/game/api/ListGameApiStepDefinition.kt
- backend/src/integrationTest/resources/features.game.api/05-list-games-api.feature
- backend/src/main/kotlin/me/elgregos/escapecamp/game/api/GameController.kt
- backend/src/main/kotlin/me/elgregos/escapecamp/game/application/GameCommandHandler.kt
- backend/src/main/kotlin/me/elgregos/escapecamp/game/application/GameService.kt
- backend/src/main/kotlin/me/elgregos/escapecamp/game/domain/entity/Game.kt
- backend/src/main/kotlin/me/elgregos/escapecamp/game/domain/repository/GameRepository.kt
- backend/src/main/kotlin/me/elgregos/escapecamp/game/infrastructure/projection/GameEntity.kt
- backend/src/main/kotlin/me/elgregos/escapecamp/game/infrastructure/projection/GameProjectionRepository.kt
- backend/src/main/kotlin/me/elgregos/escapecamp/game/infrastructure/projection/GameProjectionSubscriber.kt
- backend/src/main/resources/db/changelog/db-changelog.sql
- backend/src/test/kotlin/me/elgregos/escapecamp/game/application/GameServiceTest.kt
- backend/src/test/kotlin/me/elgregos/escapecamp/game/domain/entity/Games.kt
- backend/src/test/kotlin/me/elgregos/escapecamp/game/domain/entity/Riddles.kt
- backend/src/test/kotlin/me/elgregos/escapecamp/game/domain/event/GameAggregateCreateGameTest.kt
- backend/src/test/kotlin/me/elgregos/escapecamp/game/domain/event/GameEvents.kt
- backend/src/test/kotlin/me/elgregos/escapecamp/game/infrastructure/projection/GameEntities.kt
- backend/src/test/kotlin/me/elgregos/escapecamp/game/infrastructure/projection/GameEntityTest.kt
> ✨ Endpoints to list all games and find game by Id

- frontend/src/ec-app.ts
- frontend/src/ec-controller.ts
> ✨ End game screen

- frontend/src/ec-controller.ts
- frontend/src/ec.css
- frontend/src/styles.ts
> ✨ app notifications

- backend/src/main/kotlin/me/elgregos/escapecamp/config/sse/ServerSentEventService.kt
- backend/src/main/kotlin/me/elgregos/escapecamp/game/infrastructure/event/GameServerSentEventSubscriber.kt
- backend/src/main/resources/application.yml
> ✨ Trigger server sent event heartbeat on game created event

- backend/src/main/kotlin/me/elgregos/escapecamp/game/domain/service/RiddleSolutionChecker.kt
- backend/src/test/kotlin/me/elgregos/escapecamp/game/application/GameServiceTest.kt
> 🚸 Ignore case while checking solution

- backend/build.gradle.kts
- backend/src/main/kotlin/me/elgregos/escapecamp/config/security/SecurityConfig.kt
- frontend/index.html
> 🚸 Enable chrome notifications on mobile

- backend/src/main/kotlin/me/elgregos/escapecamp/game/infrastructure/projection/GameProjectionSubscriber.kt
> 🐛 Handle winner announced event in projection

- backend/src/main/resources/application.yml
> 🔧 Increase access token expiration

- backend/src/main/resources/application.yml
> 🔒️ Enable to overwrite organizer password

- backend/src/main/kotlin/me/elgregos/escapecamp/config/exception/ExceptionHandling.kt
- backend/src/main/kotlin/me/elgregos/escapecamp/config/security/AuthenticateController.kt
- backend/src/main/kotlin/me/elgregos/escapecamp/config/security/AuthenticatedUserService.kt
- backend/src/main/resources/application.yml
> 🐛🔒️ Check password on authentication
